import { createAsyncThunk, createSlice, PayloadAction, ThunkAction } from "@reduxjs/toolkit";
import { RootState, AppThunk, AppDispatch } from "../../app/store";
import { fetchChat } from "./chatApi";
import { Langs } from "./ChatTexts";

import { collection, query, onSnapshot, DocumentData, FirestoreError, QuerySnapshot } from "firebase/firestore";
import { fireStore } from "../../firebase-config";
import { FriendsArr, FriendsContent } from "./Chat";
import { useCollectionData } from "react-firebase-hooks/firestore";

interface ChatRooms {
  roomId: string;
  roomData: DocumentData;
  roomMessages?: { id: string; message: DocumentData }[] | null;
}
type UserRoomsArr = ChatRooms[] | null;

export interface ChatState {
  userRooms: UserRoomsArr;
  friends: FriendsArr;
  status: string;
}

const initialState: ChatState = {
  userRooms: null,
  friends: [],
  status: "idle",
};

// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const fetchUserRooms = createAsyncThunk("chat/fetchRooms", async (userId: string) => {});

export const chatSlice = createSlice({
  name: "chat",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setUserRooms: (state, action: PayloadAction<UserRoomsArr>) => {
      state.userRooms = action.payload;
    },
    setFriends: (state, action: PayloadAction<FriendsArr>) => {
      state.friends = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchUserRooms.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchUserRooms.fulfilled, (state, action) => {
        state.status = "idle";
        //state.value += action.payload;
      })
      .addCase(fetchUserRooms.rejected, (state) => {
        state.status = "failed";
      });
  },
});

export const { setUserRooms, setFriends } = chatSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectUserRooms = (state: RootState) => state.chat.userRooms;
export const selectFriends = (state: RootState) => state.chat.friends;


// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const assignTheme =
//   (): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectTheme(getState());

//     dispatch(setTheme({main: 'red'}));
//   };

export default chatSlice.reducer;
